algorithm: MSVGDd
task: dirichletMulti
# ----------
particle_num: 256
lr: 0.2
alpha: 0.02
knType: rbf
bwType: nei
bwVal: 0.1
# ----------
max_iter: 1000
time_mode: false
max_time: 120
# ----------
optim: sgd
optim_rho: 0.9
# ----------
reference_num: 2000
# ----------
eval_interval: 20
device: cuda:3
result_dir: results
time_as_dir: false
seed: 0
